---
version: "3.5"
services:
  botifactory:
    image: gitea.izzys.place/izzy/botifactory:latest
    container_name: botifactory
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - DATABASE_URL=${DATABASE_URL}
    ports:
      - 9000
    env_file:
      - .env
    restart: unless-stopped
    volumes:
      - .env:/app/.env
    networks:
      - t2_proxy
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.botifactory-rtr.rule=Host(`botifactory.izzys.place`)"
      - "traefik.http.routers.botifactory-rtr.tls=true"
      - "traefik.http.services.botifactory-rtr.loadbalancer.server.port=9000"
      - flame.type=application # "app" works too
      - flame.name=botifactory
      - flame.url=https://botifactory.izzys.place

networks:
  t2_proxy:
    name: t2_proxy
    external: true
